# Generated by Django 4.2.5 on 2023-09-29 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_order_amount_alter_coupon_code_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopinfor",
            options={
                "verbose_name": "Shop Information",
                "verbose_name_plural": "Shop Information",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="date_reviewed",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
