# Generated by Django 4.2.5 on 2023-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.IntegerField(choices=[(0, 'Trousers'), (1, 'T-shirt'), (2, 'Jacket'), (3, 'Sportswear'), (4, 'Sweater'), (5, 'Suit')], default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
