# Generated by Django 4.2.5 on 2023-09-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
