# Generated by Django 4.2.5 on 2023-10-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shopinfor_options_review_date_reviewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='accepted',
        ),
        migrations.AddField(
            model_name='refund',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
    ]
